version: "3.9"
   
services:
  db:
    image: postgres
    container_name: bmat_bo_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - djangonetwork

  api:
    container_name: bmat_bo_api
    build: .
    image: huntarhio/bo_senior_web:latest
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    links:
      - db:db
    networks:
      - djangonetwork

  api-docs:
    image: swaggerapi/swagger-ui
    container_name: bmat_bo_api_docs
    ports:
      - "8001:8080"
    volumes:
      - ./openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml


networks:
  djangonetwork:
      driver: bridge