# Generated by Django 3.2.11 on 2022-01-05 11:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_count', models.PositiveIntegerField(verbose_name='work count')),
                ('filename', models.CharField(max_length=255, null=True, verbose_name='file name')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietary_id', models.PositiveIntegerField(verbose_name='proprietary id')),
                ('iswc', models.CharField(max_length=255, null=True, verbose_name='iswc')),
                ('source', models.CharField(max_length=255, null=True, verbose_name='iswc')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='iswc')),
                ('contributors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
    ]
